Develop
shirasu-aq/todoList_TypeScript pull request #9
Opened 2021-08-04 03:06 UTC by shirasu-aq

2021-08-05 05:41 UTC, tatsuya-asami requested changes

2021-08-05 05:41 UTC, tatsuya-asami commented on src/App.tsx
> +interface Todo {
- IMO
本来どっちでも問題ない（厳密には意味合いが変わる部分もあるけど、そこまで理解して使い分けるのが難しい）のですが、全部typeで書きましょう。

2021-08-05 05:41 UTC, tatsuya-asami commented on src/App.tsx
> +  const handleOnDelete = (index: any) => {
- MUST
anyは基本なしです。本当に駄目なところだけコメントを残してanyにしましょう。

anyの修正漏れを防ぐためには、とりあえず型定義はunknownにすると良いです。

2021-08-05 14:48 UTC, shirasu-aq commented on src/App.tsx
> +interface Todo {
> 厳密には意味合いが変わる部分もあるけど、そこまで理解して使い分けるのが難しいので、全部typeで書けば良いというルールで3D K-Fieldはやっています。

承知しました！
ec4dc0b 修正しました。

参考：https://zenn.dev/luvmini511/articles/6c6f69481c2d17

2021-08-05 14:49 UTC, shirasu-aq commented on src/App.tsx
> +  const handleOnDelete = (index: any) => {
> anyは基本なしです。本当に駄目なところだけコメントを残してanyにしましょう。

承知しました。
448feb7 修正しました。

memo: https://qiita.com/suzuki_sh/items/9b168b44d1d21c127aeb

2021-08-06 02:31 UTC, tatsuya-asami commented on src/App.tsx
> +  const handleOnDelete = (index: any) => {
そういう意味ではないです〜
型指定を忘れないようにするために「とりあえず型を入れたい時はunkown」にするだけで、ここは普通にnumberが入るのではないかと思うので、その型を指定するべきです。

2021-08-06 02:32 UTC, tatsuya-asami requested changes
unkownもanyも基本は使わないです。

2021-08-09 07:50 UTC, shirasu-aq commented on src/App.tsx
> +  const handleOnDelete = (index: any) => {
e29bd22 修正しました。

2021-08-10 01:01 UTC, tatsuya-asami approved these changes

2021-08-11 00:41 UTC, merged